### ISSUE TITLE
create commands support multiple provider flags

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/executor-python#34]
With https://github.com/codeontap/gen3/pull/1166 we introduced the ability to load multiple providers as part of a template generation run. 

This ticket is to align the cli with the same feature

* multiple `-p or --generation-provider` options should be available on all create commands 
* the order of the options should be preserved and provided to the bash wrapper as multiple parameters as well

**Comment by Neketek** [comment]
@roleyfoley Not a problem at all. Probably, I will include this upgrade as part of my rewrite. Because I already completed the rewrite of ```setContext.sh``` and  ```contextTree.sh```.  The only thing that is left to rewrite is ```createTemplate.sh```. That's actually a pretty important step because after that I can start rewriting other smaller scripts and after that, I'll be able to improve them.

**Comment by roleyfoley** [comment]
Implemented in #55
